# FLOW cơ bản
# 1 : trường hợp nào chạy (trigger) chạy workflows này
# - push code trực tiếp lên branch chỉ định
# - tạo pull request vào branch chỉ định
# LƯU Ý: CHỈ TRIGGER đng folder cần chạy
# 2: checkout (lấy code mới nhất)source code mới nhất từ github
# 3 : cài môi trường java trn máy ảo (cùng version JDK trong pom)
# + lưu các cài đặt thư viện vào cache
# 4: cài browser ( chrome)
# 5: chạy test case (mvn test -Dheadless=true)

# MỘT SỐ BƯỚC NÂNG CAO (ALLURE REPORT + GỬI VỀ SLACK )
# 6: tạo allure report mỗi lần sau chạy test
# 7: tạo file allure-report.zip đ download về chạy và xem
# 8: lấy số liệu report => testng-results.xml
# 9: gửi report về slack
name: Selenium POM CI

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests
        working-directory: testing-selenium-patten   # ← THEM DONG NAY
        run: mvn test -Dbrowser=chrome -Dheadless=true

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: testing-selenium-patten/target/site/allure-maven-plugin